services:
  - type: web
    name: capstone-film-backend
    env: node
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SEED_CATALOG_ON_START
        value: "true"
